[package]
name = "speedrun-com-api"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-preview = "0.3.0-alpha.17"
hyper = { git = "https://github.com/hyperium/hyper" }
hyper-rustls = { git = "https://github.com/CryZe/hyper-rustls", branch = "tokio-0.2" }
tokio = { git = "https://github.com/tokio-rs/tokio" }
livesplit-core = "0.11.0"
derive_more = "0.15.0"
snafu = { git = "https://github.com/CryZe/snafu", branch = "print-error-chain" }
url = "1.7.2"
serde = { version = "1.0.94", features = ["derive"] }
serde_json = "1.0.40"
arrayvec = "0.4.11"
